'use strict';
const $=s=>document.querySelector(s), C=NexaCore;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n);
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'}):'—';
let data={orders:[],payments:[],expenses:[]}, tab='orders', mode='none', busy=false, refreshing=false, editing=null, credentials=null, lastSync='';
let apiUrl=localStorage.getItem('nexa-url')||window.NEXAPRINT_CONFIG.apiUrl||'';
const titles={orders:['Control de pedidos','De la primera idea a la última capa.','Tus pedidos','Filtra por fecha de entrega, tipo y estado.','+ Nuevo pedido'],summary:['Compras e ingresos','Cada movimiento, en un solo lugar.','Movimientos del periodo','Filtra por fecha del cobro o del gasto.','+ Registrar cobro'],expenses:['Gastos y costos','Conoce lo que inviertes en tu taller.','Gastos registrados','Filamentos, impresoras, insumos y otros gastos pagados.','+ Nuevo gasto'],profit:['Ganancias','Tus ingresos frente a tus gastos.','Balance de caja','Filtra por fecha de cobro y fecha de gasto.','+ Registrar cobro']};
const options=(arr,value)=>arr.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`;}).join('');
const badge=o=>{const s=C.status(o,data);return `<span class="pill ${s}">${C.labels[s]}</span>`;};
function notice(message,bad=false){$('#notice').textContent=message;$('#notice').classList.toggle('bad',bad);}
async function request(action,extra={}){
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);
 try{const r=await fetch(apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},redirect:'follow',body:JSON.stringify({action,...credentials,...extra}),signal:controller.signal});if(!r.ok)throw Error('Google respondió con un error. Revisa la implementación.');let result;try{result=await r.json();}catch{throw Error('Respuesta inesperada: verifica que la URL termine en /exec y permita acceso a Cualquier persona.');}if(!result.ok)throw Error(result.error||'No se pudo completar la operación.');return result;}catch(e){if(e.name==='AbortError')throw Error('Google tardó demasiado. Actualiza antes de reintentar: el cambio podría haberse guardado.');if(e instanceof TypeError)throw Error('No se pudo conectar. Comprueba tu conexión y la URL /exec. Actualiza antes de repetir un guardado.');throw e;}finally{clearTimeout(timer);}
}
async function refresh(silent=false){if(mode!=='live'||refreshing||busy)return;const session=credentials;refreshing=true;$('#refresh').disabled=true;$('#sync').textContent='Sincronizando…';try{const result=await request('list');if(credentials!==session||mode!=='live')return;data=result.data;lastSync=new Date().toLocaleTimeString('es-MX');$('#sync').textContent=`Actualizado ${lastSync}`;render();if(!silent)notice('Datos actualizados desde Google Sheets.');}catch(e){notice(e.message,true);$('#sync').textContent='Sin sincronizar · reintenta';}finally{refreshing=false;$('#refresh').disabled=false;}}
function filteredOrders(){return data.orders.filter(o=>{const q=$('#query').value.toLowerCase();return `${o.id} ${o.customer} ${o.description} ${o.material}`.toLowerCase().includes(q)&&(!$('#status-filter').value||C.status(o,data)===$('#status-filter').value)&&(!$('#type-filter').value||o.type===$('#type-filter').value)&&C.between(o.due,$('#from').value,$('#to').value);}).sort((a,b)=>a.due.localeCompare(b.due));}
function currentFinance(){const t=C.totals(data,$('#from').value,$('#to').value),q=$('#query').value.toLowerCase();t.expenses=t.expenses.filter(e=>`${e.concept} ${e.category} ${e.supplier}`.toLowerCase().includes(q));t.payments=t.payments.filter(p=>`${p.orderId} ${data.orders.find(o=>o.id===p.orderId)?.customer||''} ${p.note}`.toLowerCase().includes(q));t.income=t.payments.reduce((s,p)=>s+C.cents(p.amount),0)/100;t.costs=t.expenses.reduce((s,e)=>s+C.cents(e.amount),0)/100;t.net=C.cents(t.income-t.costs)/100;return t;}
function stats(items){$('#stats').innerHTML=items.map((x,i)=>`<div class="stat ${i===3?'accent':''}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');}
function table(head,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`:'<div class="empty"><strong>Todo listo para comenzar</strong>No hay registros para estos filtros.</div>';}
function render(){const title=titles[tab];$('#heading').textContent=title[0];$('#subtitle').textContent=title[1];$('#panel-title').textContent=title[2];$('#panel-help').textContent=title[3];$('#primary').textContent=title[4];$('#status-wrap').hidden=tab!=='orders';$('#type-wrap').hidden=tab!=='orders';$('#query').placeholder=tab==='orders'?'Cliente, pedido, descripción…':'Concepto, cliente, referencia…';$('#footer-mode').textContent=mode==='demo'?'Demostración local · no sincroniza':mode==='live'?`Conectado · ${credentials.user}`:'Sin datos cargados';$('#logout').hidden=mode!=='live';
 document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 if(tab==='orders'){const rows=filteredOrders();const pending=rows.filter(o=>o.stage!=='cancelled').reduce((s,o)=>s+Math.max(0,C.cents(o.price)-C.cents(C.paid(o,data))),0)/100;
 stats([['PEDIDOS',rows.length,'Según los filtros seleccionados'],['EN PRODUCCIÓN',rows.filter(o=>o.stage==='production').length,'Impresiones en curso'],['POR COBRAR',money(pending),'Saldo de pedidos no cancelados'],['POR ENTREGAR',rows.filter(o=>!['delivered','cancelled'].includes(o.stage)).length,'Órdenes abiertas']]);
 $('#content').innerHTML=table(['Pedido / cliente','Impresión','Entrega','Total / saldo','Estado','Acciones'],rows.map(o=>{const balance=Math.max(0,C.cents(o.price)-C.cents(C.paid(o,data)))/100;return `<tr><td><strong>${esc(o.customer)}</strong><span class="detail">#${esc(o.id.slice(0,8))} · ${esc(o.description)}</span></td><td>${esc(o.type)}<span class="detail">${o.quantity} pieza(s) · ${esc(o.material||'Sin material indicado')}</span></td><td>${fmt(o.due)}${o.due<today()&&!['delivered','cancelled'].includes(o.stage)?'<span class="late">Entrega vencida</span>':''}</td><td><strong>${money(o.price)}</strong><span class="detail">Saldo: ${money(balance)}</span></td><td>${badge(o)}${o.stage==='delivered'&&balance>0?'<span class="detail">Ya entregada</span>':''}</td><td><div class="compact-actions"><button class="secondary" data-edit="orders" data-id="${esc(o.id)}">Editar</button><button class="secondary" data-pay="${esc(o.id)}">Cobro</button></div></td></tr>`;}))+`<div class="legend">${Object.entries(C.labels).map(([s,l])=>`<span class="pill ${s}">${l}</span>`).join('')}</div>`;
 }else{const t=currentFinance();stats([['INGRESOS COBRADOS',money(t.income),'Cobros menos devoluciones'],['GASTOS PAGADOS',money(t.costs),'Incluye compras de equipo'],['POR COBRAR · GLOBAL',money(t.pending),'Todos los pedidos no cancelados'],['RESULTADO DE CAJA',money(t.net),'Cobros menos gastos del periodo']]);
 if(tab==='expenses'){$('#content').innerHTML=expenseTable(t.expenses);}else if(tab==='summary'){$('#content').innerHTML=`<div class="finance"><h3>Cobros y devoluciones</h3></div>`+table(['Fecha','Pedido / cliente','Importe','Nota','Acción'],t.payments.sort((a,b)=>b.date.localeCompare(a.date)).map(p=>`<tr><td>${fmt(p.date)}</td><td>${esc(data.orders.find(o=>o.id===p.orderId)?.customer||'Pedido')}<span class="detail">#${esc(p.orderId.slice(0,8))}</span></td><td>${money(p.amount)}</td><td>${esc(p.note)}</td><td><button class="secondary" data-edit="payments" data-id="${esc(p.id)}">Editar</button></td></tr>`))+`<div class="finance"><h3>Compras y gastos</h3></div>`+expenseTable(t.expenses);
 }else{const groups={};t.expenses.forEach(e=>groups[e.category]=(groups[e.category]||0)+C.cents(e.amount)/100);const months={};[...t.payments.map(p=>({...p,kind:'income'})),...t.expenses.map(e=>({...e,kind:'cost'}))].forEach(r=>{const k=r.date.slice(0,7);months[k]??={income:0,cost:0};months[k][r.kind]+=C.cents(r.amount)/100;});const max=Math.max(Math.abs(t.income),t.costs,1);$('#content').innerHTML=`<div class="finance"><div class="banner">El resultado de caja compara dinero recibido con gastos pagados, incluyendo impresoras. No representa utilidad contable ni descuenta inventario consumido, depreciación o impuestos por separado. Los anticipos cuentan en la fecha del cobro; las devoluciones restan.</div><div class="finance-grid"><div><h3>Ingresos frente a gastos</h3>${bar('Ingresos netos',t.income,max)}${bar('Gastos',t.costs,max)}</div><div><h3>Gastos por categoría</h3>${Object.entries(groups).map(([k,v])=>bar(k,v,Math.max(t.costs,1))).join('')||'<p>Sin gastos registrados en el periodo.</p>'}</div></div><h3>Resultado por mes</h3></div>`+table(['Mes','Ingresos','Gastos','Resultado'],Object.entries(months).sort(([a],[b])=>b.localeCompare(a)).map(([m,v])=>`<tr><td>${m}</td><td>${money(v.income)}</td><td>${money(v.cost)}</td><td class="${v.income-v.cost<0?'negative':''}">${money(v.income-v.cost)}</td></tr>`));}}
}
function bar(label,value,max){return `<div class="bar-row"><div><span>${esc(label)}</span><strong>${money(value)}</strong></div><div class="bar"><i style="width:${Math.min(100,Math.abs(value)/max*100)}%"></i></div></div>`;}
function expenseTable(rows){return table(['Fecha','Concepto','Categoría','Importe','Acción'],[...rows].sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<tr><td>${fmt(e.date)}</td><td><strong>${esc(e.concept)}</strong><span class="detail">${esc(e.supplier)}</span></td><td>${esc(e.category)}</td><td>${money(e.amount)}</td><td><button class="secondary" data-edit="expenses" data-id="${esc(e.id)}">Editar</button></td></tr>`));}
function field(name,label,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(name,label,values,value){return `<label>${label}<select name="${name}">${options(values,value)}</select></label>`;}
function edit(kind,id=null,orderId=null){if(mode==='none'){$('#settings').showModal();return;}const record=id?data[kind].find(x=>x.id===id):{};editing={kind,record:{...record},id:id||crypto.randomUUID()};$('#form-error').textContent='';$('#edit-title').textContent=(id?'Editar ':'Nuevo ')+({orders:'pedido',expenses:'gasto',payments:'cobro / devolución'}[kind]);const r=record;let html='';
 if(kind==='orders'){html=field('customer','Cliente',r.customer,'text','required maxlength="120"')+field('quantity','Cantidad de piezas',r.quantity||1,'number','required min="1" max="100000" step="1"')+select('type','Tipo de impresión',['FDM / Filamento','Resina','Multicolor','Otro'],r.type)+field('material','Material / color',r.material,'text','maxlength="150"')+field('description','Descripción del pedido',r.description,'text','required maxlength="300"')+field('price','Precio de venta TOTAL (MXN)',r.price,'number','required min="0" max="100000000" step="0.01"')+field('date','Fecha del pedido',r.date||today(),'date','required')+field('days','Plazo en días naturales',r.days??3,'number','required min="0" max="3650" step="1"')+field('due','Fecha de entrega',r.due||C.datePlus(today(),3),'date','required')+select('stage','Avance de la orden',[['new','Orden nueva'],['hold','En espera'],['production','En producción'],['finished','Terminada'],['delivered','Entregada'],['cancelled','Cancelada']],r.stage||'new')+`<label class="wide">Notas<textarea name="notes" maxlength="2000">${esc(r.notes)}</textarea></label><p class="muted wide">Registra anticipos y pagos con «Cobro» después de guardar el pedido. Los estados azul y rojo se calculan según el saldo. Total cobrado: ${money(id?C.paid(r,data):0)}.</p>`;
 }else if(kind==='expenses'){html=field('concept','Concepto',r.concept,'text','required maxlength="200"')+select('category','Categoría',['Filamentos','Resinas','Impresoras','Insumos','Mantenimiento','Electricidad','Envíos','Otros'],r.category)+field('amount','Gasto pagado (MXN)',r.amount,'number','required min="0" max="100000000" step="0.01"')+field('date','Fecha de pago',r.date||today(),'date','required')+field('supplier','Proveedor',r.supplier,'text','maxlength="150"')+field('note','Notas',r.note,'text','maxlength="500"');
 }else{if(!data.orders.length){notice('Primero registra un pedido para asociarle un cobro.',true);return;}html=select('orderId','Pedido',data.orders.map(o=>[o.id,`${o.customer} · ${o.description} (#${o.id.slice(0,8)})`]),r.orderId||orderId)+field('amount','Importe MXN (negativo = devolución)',r.amount,'number','required min="-100000000" max="100000000" step="0.01"')+field('date','Fecha del movimiento',r.date||today(),'date','required')+field('note','Concepto / referencia de pago',r.note,'text','required maxlength="500"')+'<p class="muted wide">Cada anticipo o liquidación es un movimiento independiente. Para corregir un movimiento, edítalo en Compras e ingresos. Importe 0 permite anular un registro erróneo conservando su historial.</p>';}
 $('#fields').innerHTML=html;if(kind==='orders'){const form=$('#edit-form');const updateDue=()=>{if(form.elements.date.value&&form.elements.days.value!=='')form.elements.due.value=C.datePlus(form.elements.date.value,form.elements.days.value);};form.elements.days.oninput=updateDue;form.elements.date.onchange=updateDue;form.elements.due.onchange=()=>{if(form.elements.due.value&&form.elements.date.value)form.elements.days.value=Math.round((new Date(form.elements.due.value+'T12:00:00Z')-new Date(form.elements.date.value+'T12:00:00Z'))/86400000);};}$('#editor').showModal();}
$('#edit-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const {kind,record,id}=editing;const values=Object.fromEntries(new FormData(e.target));for(const key of ['quantity','price','days','amount'])if(key in values)values[key]=Number(values[key]);const item={...values,id,version:record.version||0};if(kind==='orders'&&item.due<item.date){$('#form-error').textContent='La entrega no puede ser anterior al pedido.';return;}busy=true;$('#save').disabled=true;try{if(mode==='demo'){const arr=data[kind];const i=arr.findIndex(x=>x.id===id);if(kind==='payments'){const order=data.orders.find(o=>o.id===item.orderId);const net=data.payments.filter(p=>p.orderId===item.orderId&&p.id!==id).reduce((s,p)=>s+C.cents(p.amount),0)+C.cents(item.amount);if(!order||net<0||net>C.cents(order.price))throw Error('El total cobrado debe estar entre 0 y el precio del pedido.');}if(kind==='orders'&&C.cents(C.paid(item,data))>C.cents(item.price))throw Error('Registra una devolución antes de bajar el precio por debajo de lo cobrado.');item.version++;item.updatedAt=new Date().toISOString();item.updatedBy='demostración';if(i<0)arr.push(item);else arr[i]=item;localStorage.setItem('nexa-demo',JSON.stringify(data));}else{const result=await request('save',{kind,record:item});data=result.data;}$('#editor').close();notice(mode==='demo'?'Guardado en la demostración local.':'Guardado en Google Sheets.');render();}catch(err){$('#form-error').textContent=err.message;}finally{busy=false;$('#save').disabled=false;}};
$('#settings-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const url=$('#api-url').value.trim();if(!/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(url)){$('#settings-error').textContent='Pega la URL de Apps Script que termina en /exec.';return;}const old={apiUrl,credentials};apiUrl=url;credentials={user:$('#user').value,token:$('#token').value};$('#connect').disabled=true;try{const result=await request('list');data=result.data;mode='live';localStorage.setItem('nexa-url',apiUrl);$('#settings').close();$('#token').value='';$('#sync').textContent='Conectado a Google Sheets';notice('Conexión establecida. Actualización automática cada 30 segundos.');render();}catch(err){apiUrl=old.apiUrl;credentials=old.credentials;$('#settings-error').textContent=err.message;}finally{$('#connect').disabled=false;}};
function demo(){credentials=null;mode='demo';const d=today();const initial={orders:[{id:'demo-pedido-1',version:1,customer:'Mariana López',description:'Llaveros personalizados',type:'Multicolor',material:'PLA · lila / blanco',quantity:20,price:800,date:d,days:3,due:C.datePlus(d,3),stage:'production',notes:'Ejemplo de demostración'},{id:'demo-pedido-2',version:1,customer:'Estudio Creativo',description:'Prototipo de empaque',type:'Resina',material:'Resina gris',quantity:1,price:650,date:d,days:1,due:C.datePlus(d,1),stage:'finished',notes:''},{id:'demo-pedido-3',version:1,customer:'Ana Sofía',description:'Topper de cumpleaños',type:'FDM / Filamento',material:'PLA rosa',quantity:1,price:180,date:d,days:2,due:C.datePlus(d,2),stage:'new',notes:''}],payments:[{id:'demo-cobro-1',version:1,orderId:'demo-pedido-1',amount:400,date:d,note:'Anticipo'},{id:'demo-cobro-2',version:1,orderId:'demo-pedido-2',amount:650,date:d,note:'Liquidación'}],expenses:[{id:'demo-gasto-1',version:1,concept:'Bobina PLA · 1 kg',category:'Filamentos',amount:320,date:d,supplier:'Proveedor de ejemplo',note:''}]};try{data=JSON.parse(localStorage.getItem('nexa-demo'))||initial;}catch{data=initial;}$('#settings').close();$('#token').value='';$('#sync').textContent='DEMO · datos locales';notice('DEMOSTRACIÓN: los datos son ficticios y se guardan solo en este navegador. No se envían a Google Sheets.');render();}
function exportCSV(){const rows=tab==='orders'?filteredOrders().map(o=>({folio:o.id,cliente:o.customer,descripcion:o.description,tipo:o.type,piezas:o.quantity,total:o.price,cobrado:C.paid(o,data),saldo:Math.max(0,C.cents(o.price)-C.cents(C.paid(o,data)))/100,entrega:o.due,estado:C.labels[C.status(o,data)]})):tab==='expenses'?currentFinance().expenses.map(e=>({fecha:e.date,concepto:e.concept,categoria:e.category,importe:e.amount,proveedor:e.supplier})):[...currentFinance().payments.map(p=>({fecha:p.date,tipo:'Ingreso',referencia:p.orderId,concepto:p.note,importe:p.amount})),...currentFinance().expenses.map(e=>({fecha:e.date,tipo:'Gasto',referencia:e.id,concepto:e.concept,importe:-e.amount}))];if(!rows.length){notice('No hay registros para exportar.');return;}const keys=Object.keys(rows[0]);const cell=x=>'"'+(typeof x==='number'?String(x):String(x??'').replace(/^[=+\-@\t\r]/,"'$&")).replace(/"/g,'""')+'"';const csv='\uFEFF'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=`NexaPrint-${tab}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#status-filter').innerHTML+=options(Object.entries(C.labels),'');
$('#connection').onclick=()=>{$('#api-url').value=apiUrl;$('#settings-error').textContent='';$('#settings').showModal();};
$('#logout').onclick=()=>{credentials=null;mode='none';data={orders:[],expenses:[],payments:[]};$('#sync').textContent='Sesión cerrada';notice('Sesión cerrada. Conecta de nuevo para consultar tus datos.');render();};
$('#demo').onclick=demo;$('#primary').onclick=()=>edit(tab==='orders'?'orders':tab==='expenses'?'expenses':'payments');$('#refresh').onclick=()=>mode==='live'?refresh():notice(mode==='demo'?'La demostración es local y no sincroniza.':'Configura la conexión para actualizar.');$('#export').onclick=exportCSV;
$('#content').onclick=e=>{const b=e.target.closest('button');if(b?.dataset.edit)edit(b.dataset.edit,b.dataset.id);if(b?.dataset.pay)edit('payments',null,b.dataset.pay);};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;$('#query').value='';render();});
for(const id of ['query','status-filter','type-filter','from','to'])$('#'+id).addEventListener('input',()=>{if($('#from').value&&$('#to').value&&$('#from').value>$('#to').value){notice('La fecha Desde debe ser anterior a Hasta.',true);}render();});
$('#clear').onclick=()=>{['query','status-filter','type-filter','from','to'].forEach(id=>$('#'+id).value='');render();};
for(const id of ['close-editor','cancel-editor'])$('#'+id).onclick=()=>{if(!busy)$('#editor').close();};$('#editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('#close-settings').onclick=()=>$('#settings').close();
setInterval(()=>{if(mode==='live'&&!document.hidden&&!$('#editor').open&&!$('#settings').open)refresh(true);},30000);render();
